### ISSUE TITLE
[Discussion] Feedback Area Map

### ISSUE THREAD

**Issue by nikmd23** [MicrosoftDocs/vscodespaces#2]
Legend
--------
| Icon | Description |
|:-:|--------------|
| ❗ | High Priority |
| ❓ | Area of exploration ([Feedback wanted!](mailto:nik.molnar@microsoft.com)) |
| 🏃 | In Progress |
| ✔ | Complete |

Feedback Areas
==========

Environment Creation
------------------------
- [ ] 🏃 ❗ Create environments based on Windows VMs (#243)
- [ ] 🏃 Auto reload on Dockerfile changes (#51)
- [ ] 🏃  Support environments with GPUs (#192)
- [ ] Create environments based on non-Git SCMs (#17)
- [ ] Programmatic/Scriptable environment creation (#37)
- [ ] Support for environment tear down script (#121)
- [ ] Improvements to "deep link" creation experience (#135)
- [ ] Plan level defaults for environments (#142)
- [ ] Environment level support for regions (#147)
- [ ] Create environments from local directory/container (#205)
- [ ] Support for monorepos (#206)

<details><summary>✔ Completed items</summary>
  
  - [x] Improve environment creation times
  - [x] Create environments based on custom Docker image/registry (#15)
  - [x]  Create environments based on custom Dockerfile (#15)
  - [x] Create self-hosted/Server environments (#69)
  - [x] Create environments based on specific Git branches/PR/tag/commit (#7, #81)
  - [x] Make environment configuration mutable (#42)
  - [x] Create environments in selected region
  - [x] Create BYO/Desktop environments
  - [x] Create environments based on non-GitHub SCM providers
  - [x] Clone source from private Git repos

</details>

Environment Management
-----------------------------
- [ ] Improve re-connection gestures/metadata (#130)

<details><summary>✔ Completed items</summary>

  - [x] Auto suspend
  - [x] Gesture to suspend environment
  - [x] Manage all types of remote environments in one place in VS Code

</details>

Environment Personalization
-------------------------------
- [ ] 🏃 Settings synchronization across environments (#169)
- [ ] 🏃 Forward and securely access ports encrypted with self-issued dev certificates (#123)
- [ ] 🏃 Mechanism to securely pass secrets to VSO (#50, #119)
- [ ] 🏃 Auto dotfiles repo discovery (#161)
- [ ] Auto package registry registration (#162)

<details><summary>✔ Completed items</summary>

  - [x] Support terminal customization via migration from local machine
  - [x] Auto-except suggested extensions when extensions are not specified
  - [x] Support `devcontainer.json`'s `postCreateCommand`
  - [x] Support `devcontainer.json`'s `ports`
  - [x] Support `devcontainer.json`'s `extensions`
  - [x] Support terminal customizations via [dotfiles repo](https://dotfiles.github.io/)

</details>

Environment Usability
------------------------
- [ ] 🏃 Run and debug GUI applications
- [ ] 🏃 Run and debug distributed applications [docker compose, k8, etc] (#35, #40)
- [ ] ❓ Support using an environment offline (#242)
- [ ] 🏃 Improve default image for various programming languages (#46, #107)
- [ ] Enable external tooling via env file access (#202)
- [ ] Allow browsing in the web editor, without needing to create an environment (#171, #178)
- [ ] Remove terminal command limit

<details><summary>✔ Completed items</summary>

  - [x] Support running `code.exe` in CE
  - [x] Improve environment reusability 
  - [x] Open in Desktop/Open in Web

</details>

Azure Integration
-------------------
- [ ] 🏃 ❗ Support Azure users w/ multiple directories (#39)
- [ ] 🏃 ❗ VNet support (#149)
- [ ] 🏃 Improvements to Azure Portal experience for Codespaces (#198)
- [ ] Better support for Azure permissions (#64)
- [ ] Introduce Azure "Codespaces Contributor" Role (#145)
- [ ] Share plans with friends (#146)
- [ ] Azure ARM support (#188)

Team & Corporate
--------------------
- [ ] Create environments from on-premise repos (#18)

Collaboration
---------------
- [ ] Share environments with friends (#187)
- [ ] Fork environments (#191)

<details><summary>✔ Completed items</summary>

  - [x] Enable Live Share guests w/o backing environment (#178)

</details>

Web Accessible Environments
---------------------------------
- [ ] 🏃 Increase browser support footprint (#33, #34, #108)
- [ ] Make Codespaces a Progressive Web App (#43)
- [ ] 🏃 ❗ Increase scenarios supported by port forwarding (#10, #19, #105, #164, #176, #183, #193, #261)
- [ ] 🏃 ❗ Increase extension compatibility in browser (#11)

<details><summary>✔ Completed items</summary>

  - [x] Add support for creating environments via the browser from non-GitHub SCM providers (#48, #65)
  - [x] Forward and access ports via browser
  - [x] Create VSO Plan via browser (Not in Azure Portal)
  - [x] Connect to environments via browser
  - [x] Create GitHub based environments via browser
  - [x] Authenticate with Git in a secure manner
  - [x] Create and connect to environment via single click hyperlink

</details>

Cost Control
--------------
- [ ] Environment deletion improvements (#139, #151)
- [ ] More control over auto-suspend setting (#141)
- [ ] More granular usage reporting (#148)

<details><summary>✔ Completed items</summary>

  - [x] In tool plan deletion (#199)
  - [x] Increase pricing options w/ more instance types (#54 )
  - [x] Improve idle state detection (#132)

</details>

**Comment by bjlupo** [comment]
Would love the ability to associate SSH key to an environment to be able to pull private repos a little easier. Maybe use personal key vault in azure?

**Comment by colinrippeyfinarne** [comment]
Hope this is the appropriate place to add this feedback.

My scenario involves being able to select the the specific azure subscription for the plan. I work in an office where we have a production tenant that hosts all of our Azure services, Office 365 tenant, and Azure DevOps tenant (all linked to the same directory, let's call it colinprod).

I also have a totally separate colindev tenant. 

(note just making up tenant names to illustrate)

My prod account colin@colinprod.com has a Visual Studio Enterprise subscription, and I have used the benefits that come with this subscription to associate the Azure $150 per month benefit to the colindev tenant.

My colin@colinprod.com account is a B2B guest on colindev and is an Owner of the Visual Studio Enterprise subscription, thus having a budget of $150 to dev/test various Azure services.

I want to be able to to go https://online.visualstudio.com, sign in as colin@colinprod.com and be able to select the Visual Studio Enterprise subscription from colindev.

At the moment I only seem to be able to see the Azure subscriptions I have access to on colinprod, not any subscriptions I see on colindev.

I want this scenario to work as all of our source code is maintained on the Azure DevOps tenant that is hosted on the colinprod diretory, and my login colin@colinprod.com has access to the repos.

**Comment by jkeech** [comment]
@colinrippeyfinarne, thanks for the detailed information. The ability to sign into multiple directories/tenants is being tracked at #39. We are actively working on this feature and hope to roll it out soon. Thanks!

**Comment by YuyingWu** [comment]
Any plans for the localization of the docs? Like `vsonline.zh-cn`.I volunteer for the translation :)

**Comment by jgbradley1** [comment]
Can someone edit the area map and link in issues corresponding to each bullet point so we can all track the conversations?

**Comment by nikmd23** [comment]
Hey @jgbradley1! This is on my to do, I'll make it happen ASAP - thanks for the reminder. 😉

**Comment by nikmd23** [comment]
And the issues have been linked! ✅

**Comment by PeterMilovcik** [comment]
How can one run and connect to blazor app in VS online in browser? 
By default it's listening on https://localhost:5001 and 5000 which is not working in this remote env.

**Comment by nikmd23** [comment]
Hi @PeterMilovcik. We’re you able to forward those two ports?

**Comment by PeterMilovcik** [comment]
> Hi @PeterMilovcik. We’re you able to forward those two ports? (See here: https://docs.microsoft.com/en-us/visualstudio/online/how-to/browser#port-forwarding)

Thanks a lot for the link, I did try to forward 5001 and 5000 localhost as described in article, but I got:
too long to respond. HTTP ERROR 504

**Comment by nvick** [comment]
Is it possible to use private container registries in Dockerfiles for custom VS Online environments?

**Comment by pieterdv** [comment]
Can you provide more details around 'Run and debug GUI applications'? Since this seems in progress but there is no linked issue

**Comment by jabbera** [comment]
Hi,

Any update on the progress of https://github.com/MicrosoftDocs/vsonline/issues/149?

Cheers!

**Comment by lostintangent** [comment]
Closing this issue since we'll be tracking feedback via the [GitHub Community Forum](https://github.community/c/codespaces-beta/45) moving forward. Thanks!
